name: YouTube HLS Downloader

on:
  schedule:
    - cron: '0 */6 * * *'  # Her 6 saatte bir (UTC)
  workflow_dispatch:      # Elle tetiklemek için

jobs:
  download_hls:
    runs-on: ubuntu-latest

    steps:
      - name: Repoyu çek
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Gerekli paketleri yükle
        run: pip install requests

      - name: HLS manifest'leri al ve M3U playlist oluştur
        run: python m3utojson.py

      - name: M3U playlist'ini oluştur
        run: python create_playlist.py

      - name: Değişiklikleri commit et ve push yap
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add m3u8/*.m3u8
          git add playlist.m3u
          git diff --cached --quiet || (git commit -m "Update HLS manifests and playlist [skip ci]" && git push)
