name: YouTube HLS Downloader

on:
  schedule:
    - cron: '0 */6 * * *'  # Her 6 saatte bir (UTC)
  workflow_dispatch:      # Elle tetiklemek için

jobs:
  download_hls:
    runs-on: ubuntu-latest

    steps:
      - name: Repoyu çek
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Tüm commit geçmişini çek

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Gerekli paketleri yükle
        run: pip install requests

      - name: HLS manifest'leri al
        run: python m3utojson.py

      - name: M3U playlist'ini oluştur
        run: python create_playlist.py

      - name: Değişiklikleri kontrol et ve commit et
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Değişiklik olup olmadığını kontrol et
          if git diff --quiet --exit-code; then
            echo "Değişiklik yok, commit atlanıyor."
          else
            # Tüm yeni dosyaları ve değişen dosyaları ekle
            git add .
            git commit -m "Update HLS manifests and playlist [skip ci]"
            git push
          fi
