name: YouTube M3U Playlist Creator

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  create_m3u:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu çek
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: M3U playlist oluştur
        run: python create_m3u.py

      - name: Değişiklikleri commit et ve push yap
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *.m3u
          git diff --cached --quiet || (git commit -m "Update M3U playlist [skip ci]" && git push)
