name: YouTube HLS Downloader with yt-dlp

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  download_hls:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu çek
        uses: actions/checkout@v4

      - name: yt-dlp'yi yükle
        run: pip install yt-dlp

      - name: M3U8 linklerini al
        run: python yt_m3u8_downloader.py

      - name: M3U playlist'ini oluştur
        run: python create_playlist.py

      - name: Değişiklikleri commit et ve push yap
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add m3u8/*.m3u8
          git add playlist.m3u
          git diff --cached --quiet || (git commit -m "Update HLS manifests and playlist [skip ci]" && git push)
